name: feds
description: Flutter External Datasource.
version: 0.1.5
homepage: https://github.com/gabrielgits/feds.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  shared_preferences: ^2.2.1
  http: ^1.2.1
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0