name: feds
description: Flutter External Datasource.

version: 0.1.0
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  dio: ^5.3.3
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0